from handlers.start import dp
from handlers.admin_handler import dp
from handlers.dishes_handler import dp
from handlers.basket_handler import dp
from handlers.payment_handler import dp
from handlers.back_in_main_menu import dp
from handlers.statistic import dp
from handlers.base_handler import dp
from handlers.profile_handler import dp
from handlers.admin_changes import dp
from handlers.chefs_changes import dp
from handlers.pay_offline import dp
from handlers.admin_accept_order import dp
from handlers.chef_handler import dp
from handlers.black_list_handler import dp
from handlers.newsletter import dp